name: Generate FatJar

on:
  workflow_dispatch:


jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.3.3'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run customFatJar task
        run: ./gradlew customFatJar

      - name: List contents of build/libs directory
        run: ls -l build/libs

      - name: Upload FatJar as artifact
        uses: actions/upload-artifact@v2
        with:
          name: customFatJarArtifact
          path: ${{ github.workspace }}/build/libs/

