name: Generate FatJar

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Set your desired Java version

      - name: Build custom FatJar
        run: |
          chmod +x gradlew  # Ensure gradlew is executable
          ./gradlew customFatJar
