name: Jpackage Windows

on:
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: windows-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.3.3'

      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Change wrapper permissions
        run: powershell Set-ExecutionPolicy Unrestricted -Scope Process -Force; ./gradlew.bat

      - name: Run customFatJar task
        run: ./gradlew customFatJar

      - name: List contents of build/libs directory
        run: dir build\libs

      - name: Check jpackage availability
        run: jpackage --input build\libs\ --name PackageDemo --main-jar PackageDemoJAR-1.0-SNAPSHOT.jar --main-class com.heshanthenura.packagedemo.Launcher --type msi --win-dir-chooser --dest build\win\ --win-menu --win-shortcut --app-version 1.0 --vendor "Heshan Thenura"

      - name: List contents of build/win directory
        run: dir build\win

      - name: Upload MSI
        uses: actions/upload-artifact@v2
        with:
          name: PackageDemo
          path: build\win\

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0  # Set your desired tag name for the release
          release_name: JpackageDemo-win  # Set your desired release name
          draft: false
          prerelease: false

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: false
#          prerelease: false