name: Jpackage Windows

on:
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: windows-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '7.3.3'

      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Change wrapper permissions
        run: powershell Set-ExecutionPolicy Unrestricted -Scope Process -Force; ./gradlew.bat

      - name: Run customFatJar task
        run: ./gradlew customFatJar

      - name: List contents of build/libs directory
        run: dir build\libs

      - name: Check jpackage availability
        run: jpackage --version
